site_name: SDP Meeting Minute
markdown_extensions:
  - footnotes
  - admonition
  - codehilite
  #- pymdownx.mark
  #- pymdownx.tabbed
  #- pymdownx.tasklist:
  #    custom_checkbox: true
  #- pymdownx.progressbar
  #- pymdownx.tilde
# plugins:
#  - search # necessary for search to work
#  - git-revision-date-localized:
#        type: timeago
  
extra_css:
  - stylesheets/extra.css
